In [1]:
import pandas as pd
import numpy as np

# 한글 폰트 깨짐 방지
from matplotlib import font_manager, rc
font_path = "C:/Windows/Fonts/NGULIM.TTF"
font = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font)

#에러 무시
import warnings
warnings.filterwarnings('ignore')

import pandas as pd

import matplotlib.pyplot as plt
import matplotlib

from sklearn.tree import export_graphviz
import graphviz

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import scale, minmax_scale, robust_scale, StandardScaler

import xgboost as xgb

import seaborn as sns

plt.rcParams['font.family'] = 'NanumGothic'

In [86]:
hts = pd.read_csv('f0910_hts.csv', encoding = 'cp949')
hts.drop('Unnamed: 0', axis = 1, inplace = True)

In [87]:
hitter = pd.read_csv('f0913_final_hitter.csv', encoding = 'cp949')

In [88]:
hts.head(1)

연도  월           경기코드           타구코드   선수코드 타자 팀 코드  이닝   타구속도  발사각도 타격결과  \
0  2018  3  20180324HHWO0  180324_140436  62797      HH   1  131.5  42.7  플라이   

     투구구속 해당구장  안타여부  장타여부    파생_발사각도    표준화_속도    표준화_각도        파생변수  \
0  149.59   고척     0     0  78.322842  0.488539  0.695866  209.822842   

   표준화_파생변수  배럴여부  
0  1.184405     0

1. 양의지 : 76232
2. 강백호 : 68050
3. 최정 : 75847
4. 이정후 : 67341
5. 채은성 : 79192
6. 김재환 : 78224
7. 전준우 : 78513
8. 김현수 : 76290
9. 박건우 : 79215
10. 로맥 : 67872

In [89]:
plr1 = hts[hts['선수코드'] == 76232]
plr2 = hts[hts['선수코드'] == 68050]
plr3 = hts[hts['선수코드'] == 75847]
plr4 = hts[hts['선수코드'] == 67341]
plr5 = hts[hts['선수코드'] == 79192]
plr6 = hts[hts['선수코드'] == 78224]
plr7 = hts[hts['선수코드'] == 78513]
plr8 = hts[hts['선수코드'] == 76290]
plr9 = hts[hts['선수코드'] == 79215]
plr10 = hts[hts['선수코드'] == 67872]

plr = [plr1,plr2,plr3,plr4,plr5,plr6,plr7,plr8,plr9,plr10]

for i in plr:
    i.reset_index(inplace = True, drop = True)

In [90]:
plr1_18 = plr1[plr1['연도'] == 2018]
plr1_18['안타수'] = plr1_18['안타여부'].cumsum()
plr1_19 = plr1[plr1['연도'] == 2019]
plr1_19['안타수'] = plr1_19['안타여부'].cumsum()
plr1_20 = plr1[plr1['연도'] == 2020]
plr1_20['안타수'] = plr1_20['안타여부'].cumsum()
plr1_21 = plr1[plr1['연도'] == 2021]
plr1_21['안타수'] = plr1_21['안타여부'].cumsum()

plr2_18 = plr2[plr2['연도'] == 2018]
plr2_18['안타수'] = plr2_18['안타여부'].cumsum()
plr2_19 = plr2[plr2['연도'] == 2019]
plr2_19['안타수'] = plr2_19['안타여부'].cumsum()
plr2_20 = plr2[plr2['연도'] == 2020]
plr2_20['안타수'] = plr2_20['안타여부'].cumsum()
plr2_21 = plr2[plr2['연도'] == 2021]
plr2_21['안타수'] = plr2_21['안타여부'].cumsum()

plr3_18 = plr3[plr3['연도'] == 2018]
plr3_18['안타수'] = plr3_18['안타여부'].cumsum()
plr3_19 = plr3[plr3['연도'] == 2019]
plr3_19['안타수'] = plr3_19['안타여부'].cumsum()
plr3_20 = plr3[plr3['연도'] == 2020]
plr3_20['안타수'] = plr3_20['안타여부'].cumsum()
plr3_21 = plr3[plr3['연도'] == 2021]
plr3_21['안타수'] = plr3_21['안타여부'].cumsum()

plr4_18 = plr4[plr4['연도'] == 2018]
plr4_18['안타수'] = plr4_18['안타여부'].cumsum()
plr4_19 = plr4[plr4['연도'] == 2019]
plr4_19['안타수'] = plr4_19['안타여부'].cumsum()
plr4_20 = plr4[plr4['연도'] == 2020]
plr4_20['안타수'] = plr4_20['안타여부'].cumsum()
plr4_21 = plr4[plr4['연도'] == 2021]
plr4_21['안타수'] = plr4_21['안타여부'].cumsum()

plr5_18 = plr5[plr5['연도'] == 2018]
plr5_18['안타수'] = plr5_18['안타여부'].cumsum()
plr5_19 = plr5[plr5['연도'] == 2019]
plr5_19['안타수'] = plr5_19['안타여부'].cumsum()
plr5_20 = plr5[plr5['연도'] == 2020]
plr5_20['안타수'] = plr5_20['안타여부'].cumsum()
plr5_21 = plr5[plr5['연도'] == 2021]
plr5_21['안타수'] = plr5_21['안타여부'].cumsum()

plr6_18 = plr6[plr6['연도'] == 2018]
plr6_18['안타수'] = plr6_18['안타여부'].cumsum()
plr6_19 = plr6[plr6['연도'] == 2019]
plr6_19['안타수'] = plr6_19['안타여부'].cumsum()
plr6_20 = plr6[plr6['연도'] == 2020]
plr6_20['안타수'] = plr6_20['안타여부'].cumsum()
plr6_21 = plr6[plr6['연도'] == 2021]
plr6_21['안타수'] = plr6_21['안타여부'].cumsum()

plr7_18 = plr7[plr7['연도'] == 2018]
plr7_18['안타수'] = plr7_18['안타여부'].cumsum()
plr7_19 = plr7[plr7['연도'] == 2019]
plr7_19['안타수'] = plr7_19['안타여부'].cumsum()
plr7_20 = plr7[plr7['연도'] == 2020]
plr7_20['안타수'] = plr7_20['안타여부'].cumsum()
plr7_21 = plr7[plr7['연도'] == 2021]
plr7_21['안타수'] = plr7_21['안타여부'].cumsum()

plr8_18 = plr8[plr8['연도'] == 2018]
plr8_18['안타수'] = plr8_18['안타여부'].cumsum()
plr8_19 = plr8[plr8['연도'] == 2019]
plr8_19['안타수'] = plr8_19['안타여부'].cumsum()
plr8_20 = plr8[plr8['연도'] == 2020]
plr8_20['안타수'] = plr8_20['안타여부'].cumsum()
plr8_21 = plr8[plr8['연도'] == 2021]
plr8_21['안타수'] = plr8_21['안타여부'].cumsum()

plr9_18 = plr9[plr9['연도'] == 2018]
plr9_18['안타수'] = plr9_18['안타여부'].cumsum()
plr9_19 = plr9[plr9['연도'] == 2019]
plr9_19['안타수'] = plr9_19['안타여부'].cumsum()
plr9_20 = plr9[plr9['연도'] == 2020]
plr9_20['안타수'] = plr9_20['안타여부'].cumsum()
plr9_21 = plr9[plr9['연도'] == 2021]
plr9_21['안타수'] = plr9_21['안타여부'].cumsum()

plr10_18 = plr10[plr10['연도'] == 2018]
plr10_18['안타수'] = plr10_18['안타여부'].cumsum()
plr10_19 = plr10[plr10['연도'] == 2019]
plr10_19['안타수'] = plr10_19['안타여부'].cumsum()
plr10_20 = plr10[plr10['연도'] == 2020]
plr10_20['안타수'] = plr10_20['안타여부'].cumsum()
plr10_21 = plr10[plr10['연도'] == 2021]
plr10_21['안타수'] = plr10_21['안타여부'].cumsum()

plr1 = pd.concat([plr1_18, plr1_19, plr1_20, plr1_21])
plr2 = pd.concat([plr2_18, plr2_19, plr2_20, plr2_21])
plr3 = pd.concat([plr3_18, plr3_19, plr3_20, plr3_21])
plr4 = pd.concat([plr4_18, plr4_19, plr4_20, plr4_21])
plr5 = pd.concat([plr5_18, plr5_19, plr5_20, plr5_21])
plr6 = pd.concat([plr6_18, plr6_19, plr6_20, plr6_21])
plr7 = pd.concat([plr7_18, plr7_19, plr7_20, plr7_21])
plr8 = pd.concat([plr8_18, plr8_19, plr8_20, plr8_21])
plr9 = pd.concat([plr9_18, plr9_19, plr9_20, plr9_21])
plr10 = pd.concat([plr10_18, plr10_19, plr10_20, plr10_21])

In [92]:
plr1.head()

연도  월           경기코드           타구코드   선수코드 타자 팀 코드  이닝    타구속도  발사각도  \
0  2018  3  20180324SSOB0  180324_143531  76232      OB   2  154.86  -1.2   
1  2018  3  20180324SSOB0  180324_153656  76232      OB   5  156.38  16.3   
2  2018  3  20180324SSOB0  180324_161310  76232      OB   7  159.94  -5.6   
3  2018  3  20180324SSOB0  180324_170918  76232      OB   9  158.22  -8.3   
4  2018  3  20180325SSOB0  180325_143045  76232      OB   1  130.49 -11.4   

   타격결과  ...  해당구장 안타여부  장타여부    파생_발사각도    표준화_속도    표준화_각도        파생변수  \
0   1루타  ...    잠실    1     1  77.777158  0.711652  0.688202  232.637158   
1   2루타  ...    잠실    1     2  95.277158  0.726170  0.933989  251.657158   
2   2루타  ...    잠실    1     2  73.377158  0.760172  0.626404  233.317158   
3  땅볼아웃  ...    잠실    0     0  70.677158  0.743744  0.588483  228.897158   
4   병살타  ...    잠실    0     0  67.577158  0.478892  0.544944  198.067158   

   표준화_파생변수  배럴여부  안타수  
0  1.399855     0    1  
1  1.660159     1    2  
2  1.386576     0    3  
3  1.332227     0    3  
4  1.023836     0    3  

[5 rows x 21 columns]

In [94]:
hitter['배럴지수_평균'] = 0

In [98]:
hitter

연도   선수코드  경기수   타석   타수     타율  안타  홈런   루타    장타율  ...       OPS  \
0    2018  60100   70  169  152  0.243  37   3   63  0.414  ...  0.727609   
1    2018  60184    6   10   10  0.200   2   0    3  0.300  ...  0.500000   
2    2018  60343   83  174  162  0.216  35   8   63  0.389  ...  0.654896   
3    2018  60523   91  194  174  0.305  53   7   86  0.494  ...  0.854825   
4    2018  60558  128  374  342  0.254  87  12  144  0.421  ...  0.730973   
..    ...    ...  ...  ...  ...    ...  ..  ..  ...    ...  ...       ...   
921  2021  79240   69  301  279  0.323  90   4  122  0.437  ...  0.805771   
922  2021  79365   73  261  219  0.265  58  16  117  0.534  ...  0.906093   
923  2021  79402   70  278  237  0.211  50   1   61  0.257  ...  0.564407   
924  2021  79456   62  135  124  0.274  34   0   38  0.306  ...  0.619433   
925  2021  79608   55  246  212  0.325  69   5  102  0.481  ...  0.871947   

     배럴갯수      배럴비율  선수명  도루  도실   wOBA   wRC+  WAR+  배럴지수_평균  
0      16  0.094675  백진우   0   0  0.320   79.1 -0.11        0  
1       1  0.100000  김창혁   0   0  0.216   12.5 -0.05        0  
2      13  0.074713  이해창   0   3  0.282   54.5 -0.15        0  
3      26  0.134021   정훈   4   2  0.367  110.7  0.91        0  
4      32  0.085561  오태곤  13   8  0.317   76.5 -0.10        0  
..    ...       ...  ...  ..  ..    ...    ...   ...      ...  
921    28  0.093023  허경민   2   4  0.342  102.2  1.71        0  
922    30  0.114943  박동원   1   0  0.392  138.8  2.85        0  
923     9  0.032374  김상수   0   0    NaN    NaN  0.00        0  
924     6  0.044444  이지영   2   1  0.279   55.9 -0.16        0  
925    22  0.089431  안치홍   3   4  0.381  121.1  2.08        0  

[926 rows x 27 columns]

In [95]:
hitter18 = hitter.loc[(hitter['연도'] == 2018)]
hitter19 = hitter.loc[(hitter['연도'] == 2019)]
hitter20 = hitter.loc[(hitter['연도'] == 2020)]
hitter21 = hitter.loc[(hitter['연도'] == 2021)]

In [104]:
hts18 = hts[hts['연도'] == 2018]
pcode = hitter18['선수코드'].unique()
barrel = []
for code in pcode:
    barrel.append(hts18[hts18['선수코드']== code ]['표준화_파생변수'].mean())   
hitter18['배럴지수_평균'] = barrel


hts19 = hts[hts['연도'] == 2019]
pcode = hitter19['선수코드'].unique()
barrel = []
for code in pcode:
    barrel.append(hts19[hts19['선수코드']== code ]['표준화_파생변수'].mean())   
hitter19['배럴지수_평균'] = barrel


hts20 = hts[hts['연도'] == 2020]
pcode = hitter20['선수코드'].unique()
barrel = []
for code in pcode:
    barrel.append(hts20[hts20['선수코드']== code ]['표준화_파생변수'].mean())    
hitter20['배럴지수_평균'] = barrel


hts21 = hts[hts['연도'] == 2021]
pcode = hitter21['선수코드'].unique()
barrel = []
for code in pcode:
    barrel.append(hts21[hts21['선수코드']== code ]['표준화_파생변수'].mean())   
hitter21['배럴지수_평균'] = barrel

In [105]:
hitter = pd.concat([hitter18, hitter19, hitter20, hitter21])

In [107]:
hitter.head(1)

연도   선수코드  경기수   타석   타수     타율  안타  홈런  루타    장타율  ...       OPS  배럴갯수  \
0  2018  60100   70  169  152  0.243  37   3  63  0.414  ...  0.727609    16   

       배럴비율  선수명  도루  도실  wOBA  wRC+  WAR+   배럴지수_평균  
0  0.094675  백진우   0   0  0.32  79.1 -0.11  1.244363  

[1 rows x 27 columns]

In [123]:
# hitter[hitter['선수명']] == '양의지'
hitter[hitter['선수명'] == '강백호']['배럴지수_평균'].mean()

1.3199973027352994

In [219]:
test = pd.DataFrame({'경기수':[144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
                             '배럴지수_평균':[hitter[hitter['선수명'] =='양의지']['배럴지수_평균'].mean(), 
                                        hitter[hitter['선수명'] == '강백호']['배럴지수_평균'].mean(), 
                                        hitter[hitter['선수명'] == '최정']['배럴지수_평균'].mean(),
                                       hitter[hitter['선수명'] == '이정후']['배럴지수_평균'].mean(),
                                       hitter[hitter['선수명'] == '채은성']['배럴지수_평균'].mean(),
                                       hitter[hitter['선수명'] == '김재환']['배럴지수_평균'].mean(),
                                       hitter[hitter['선수명'] == '전준우']['배럴지수_평균'].mean(),
                                       hitter[hitter['선수명'] == '김현수']['배럴지수_평균'].mean(),
                                       hitter[hitter['선수명'] == '박건우']['배럴지수_평균'].mean(),
                                       hitter[hitter['선수명'] == '로맥']['배럴지수_평균'].mean()],
                    '배럴비율' : [hitter[hitter['선수명'] == '양의지']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '강백호']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '최정']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '이정후']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '채은성']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '김재환']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '전준우']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '김현수']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '박건우']['배럴비율'].mean(),
                             hitter[hitter['선수명'] == '로맥']['배럴비율'].mean()]})
test

경기수   배럴지수_평균      배럴비율
0  144  1.305213  0.163905
1  144  1.319997  0.138354
2  144  1.276051  0.124472
3  144  1.277694  0.098911
4  144  1.288991  0.147066
5  144  1.364431  0.161957
6  144  1.282912  0.123370
7  144  1.323903  0.158135
8  144  1.318927  0.147725
9  144  1.289769  0.134671

In [220]:
hitter.columns

Index(['연도', '선수코드', '경기수', '타석', '타수', '타율', '안타', '홈런', '루타', '장타율', '희생플라이',
       '볼넷', '삼진', '고의4구', '사구', '병살타', '출루율', 'OPS', '배럴갯수', '배럴비율', '선수명',
       '도루', '도실', 'wOBA', 'wRC+', 'WAR+', '배럴지수_평균'],
      dtype='object')

In [221]:
# 
df_raw_y = hitter[['타수']]# 목표변수
df_raw_x = hitter[['경기수', '배럴지수_평균', '배럴비율']] # 독립변수

# train, test set 나누기
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_x, df_raw_y, test_size = 0.3, random_state = 1234)

print('train data x size : {}'.format(df_train_x.shape))
print('train data y size : {}'.format(df_train_y.shape))
print('test data x size : {}'.format(df_test_x.shape))
print('test data y size : {}'.format(df_test_y.shape))

xgb_final = xgb.XGBRegressor(random_state = 1234)

xgb_final.fit(df_train_x, df_train_y)
print('----------------------------')
print('Score on training set: {:.3f}'.format(xgb_final.score(df_train_x, df_train_y)))
print('Score on test set: {:.3f}'.format(xgb_final.score(df_test_x, df_test_y)))

train data x size : (648, 3)
train data y size : (648, 1)
test data x size : (278, 3)
test data y size : (278, 1)
----------------------------
Score on training set: 1.000
Score on test set: 0.888


In [222]:
df_t = test
pred = xgb_final.predict(df_t)
pred

array([536.263  , 541.6694 , 558.7855 , 536.9605 , 551.1458 , 541.639  ,
       553.4271 , 543.40247, 544.85126, 543.1802 ], dtype=float32)

In [223]:
df_t['타수'] = pred

In [224]:
df_t

경기수   배럴지수_평균      배럴비율          타수
0  144  1.305213  0.163905  536.263000
1  144  1.319997  0.138354  541.669373
2  144  1.276051  0.124472  558.785522
3  144  1.277694  0.098911  536.960510
4  144  1.288991  0.147066  551.145813
5  144  1.364431  0.161957  541.638977
6  144  1.282912  0.123370  553.427124
7  144  1.323903  0.158135  543.402466
8  144  1.318927  0.147725  544.851257
9  144  1.289769  0.134671  543.180176

In [225]:
# 
df_raw_y = hitter[['안타']]# 목표변수
df_raw_x = hitter[['경기수', '배럴지수_평균', '배럴비율', '타수']] # 독립변수

# train, test set 나누기
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_x, df_raw_y, test_size = 0.3, random_state = 1234)

print('train data x size : {}'.format(df_train_x.shape))
print('train data y size : {}'.format(df_train_y.shape))
print('test data x size : {}'.format(df_test_x.shape))
print('test data y size : {}'.format(df_test_y.shape))

xgb_final = xgb.XGBRegressor(random_state = 1234)

xgb_final.fit(df_train_x, df_train_y)
print('----------------------------')
print('Score on training set: {:.3f}'.format(xgb_final.score(df_train_x, df_train_y)))
print('Score on test set: {:.3f}'.format(xgb_final.score(df_test_x, df_test_y)))

train data x size : (648, 4)
train data y size : (648, 1)
test data x size : (278, 4)
test data y size : (278, 1)
----------------------------
Score on training set: 1.000
Score on test set: 0.974


In [226]:
df_t = test
pred = xgb_final.predict(df_t)
pred

array([170.2967 , 164.82231, 175.7032 , 157.94748, 174.88895, 153.36427,
       173.80148, 183.06671, 172.98813, 169.3301 ], dtype=float32)

In [227]:
df_t['안타'] = pred
df_t

경기수   배럴지수_평균      배럴비율          타수          안타
0  144  1.305213  0.163905  536.263000  170.296707
1  144  1.319997  0.138354  541.669373  164.822311
2  144  1.276051  0.124472  558.785522  175.703201
3  144  1.277694  0.098911  536.960510  157.947479
4  144  1.288991  0.147066  551.145813  174.888947
5  144  1.364431  0.161957  541.638977  153.364273
6  144  1.282912  0.123370  553.427124  173.801483
7  144  1.323903  0.158135  543.402466  183.066711
8  144  1.318927  0.147725  544.851257  172.988129
9  144  1.289769  0.134671  543.180176  169.330093

In [228]:
# 
df_raw_y = hitter[['루타']]# 목표변수
df_raw_x = hitter[['경기수', '배럴지수_평균', '배럴비율', '타수', '안타']] # 독립변수

# train, test set 나누기
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_x, df_raw_y, test_size = 0.3, random_state = 1234)

print('train data x size : {}'.format(df_train_x.shape))
print('train data y size : {}'.format(df_train_y.shape))
print('test data x size : {}'.format(df_test_x.shape))
print('test data y size : {}'.format(df_test_y.shape))

xgb_final = xgb.XGBRegressor(random_state = 1234)

xgb_final.fit(df_train_x, df_train_y)
print('----------------------------')
print('Score on training set: {:.3f}'.format(xgb_final.score(df_train_x, df_train_y)))
print('Score on test set: {:.3f}'.format(xgb_final.score(df_test_x, df_test_y)))

train data x size : (648, 5)
train data y size : (648, 1)
test data x size : (278, 5)
test data y size : (278, 1)
----------------------------
Score on training set: 1.000
Score on test set: 0.977


In [229]:
pred = xgb_final.predict(df_t)
pred

array([314.0717 , 279.6125 , 300.9119 , 246.56044, 319.2634 , 260.94046,
       301.09167, 310.31827, 327.68292, 311.36194], dtype=float32)

In [230]:
df_t['루타'] = pred
df_t

경기수   배럴지수_평균      배럴비율          타수          안타          루타
0  144  1.305213  0.163905  536.263000  170.296707  314.071686
1  144  1.319997  0.138354  541.669373  164.822311  279.612488
2  144  1.276051  0.124472  558.785522  175.703201  300.911896
3  144  1.277694  0.098911  536.960510  157.947479  246.560440
4  144  1.288991  0.147066  551.145813  174.888947  319.263397
5  144  1.364431  0.161957  541.638977  153.364273  260.940460
6  144  1.282912  0.123370  553.427124  173.801483  301.091675
7  144  1.323903  0.158135  543.402466  183.066711  310.318268
8  144  1.318927  0.147725  544.851257  172.988129  327.682922
9  144  1.289769  0.134671  543.180176  169.330093  311.361938

In [231]:
# 
df_raw_y = hitter[['볼넷']]# 목표변수
df_raw_x = hitter[['경기수', '배럴지수_평균', '배럴비율', '타수', '안타', '루타']] # 독립변수

# train, test set 나누기
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_x, df_raw_y, test_size = 0.3, random_state = 1234)

print('train data x size : {}'.format(df_train_x.shape))
print('train data y size : {}'.format(df_train_y.shape))
print('test data x size : {}'.format(df_test_x.shape))
print('test data y size : {}'.format(df_test_y.shape))

xgb_final = xgb.XGBRegressor(random_state = 1234)

xgb_final.fit(df_train_x, df_train_y)
print('----------------------------')
print('Score on training set: {:.3f}'.format(xgb_final.score(df_train_x, df_train_y)))
print('Score on test set: {:.3f}'.format(xgb_final.score(df_test_x, df_test_y)))

train data x size : (648, 6)
train data y size : (648, 1)
test data x size : (278, 6)
test data y size : (278, 1)
----------------------------
Score on training set: 1.000
Score on test set: 0.777


In [232]:
pred = xgb_final.predict(df_t)
pred

array([46.436382, 62.531487, 45.703114, 64.60764 , 51.905193, 65.11055 ,
       54.246502, 61.551853, 54.18547 , 61.94344 ], dtype=float32)

In [233]:
df_t['볼넷'] = pred
df_t

경기수   배럴지수_평균      배럴비율          타수          안타          루타         볼넷
0  144  1.305213  0.163905  536.263000  170.296707  314.071686  46.436382
1  144  1.319997  0.138354  541.669373  164.822311  279.612488  62.531487
2  144  1.276051  0.124472  558.785522  175.703201  300.911896  45.703114
3  144  1.277694  0.098911  536.960510  157.947479  246.560440  64.607643
4  144  1.288991  0.147066  551.145813  174.888947  319.263397  51.905193
5  144  1.364431  0.161957  541.638977  153.364273  260.940460  65.110550
6  144  1.282912  0.123370  553.427124  173.801483  301.091675  54.246502
7  144  1.323903  0.158135  543.402466  183.066711  310.318268  61.551853
8  144  1.318927  0.147725  544.851257  172.988129  327.682922  54.185471
9  144  1.289769  0.134671  543.180176  169.330093  311.361938  61.943439

In [234]:
# 
df_raw_y = hitter[['사구']]# 목표변수
df_raw_x = hitter[['경기수', '배럴지수_평균', '배럴비율', '타수', '안타', '루타', '볼넷']] # 독립변수

# train, test set 나누기
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_x, df_raw_y, test_size = 0.3, random_state = 1234)

print('train data x size : {}'.format(df_train_x.shape))
print('train data y size : {}'.format(df_train_y.shape))
print('test data x size : {}'.format(df_test_x.shape))
print('test data y size : {}'.format(df_test_y.shape))

xgb_final = xgb.XGBRegressor(random_state = 1234)

xgb_final.fit(df_train_x, df_train_y)
print('----------------------------')
print('Score on training set: {:.3f}'.format(xgb_final.score(df_train_x, df_train_y)))
print('Score on test set: {:.3f}'.format(xgb_final.score(df_test_x, df_test_y)))

train data x size : (648, 7)
train data y size : (648, 1)
test data x size : (278, 7)
test data y size : (278, 1)
----------------------------
Score on training set: 1.000
Score on test set: 0.322


In [235]:
pred = xgb_final.predict(df_t)
pred

array([13.747844 ,  4.1883216, 13.153437 ,  6.894721 , 12.905494 ,
        3.1430798, 13.077097 ,  8.934321 , 13.575776 , 15.627257 ],
      dtype=float32)

In [236]:
df_t['사구'] = pred
df_t

경기수   배럴지수_평균      배럴비율          타수          안타          루타         볼넷  \
0  144  1.305213  0.163905  536.263000  170.296707  314.071686  46.436382   
1  144  1.319997  0.138354  541.669373  164.822311  279.612488  62.531487   
2  144  1.276051  0.124472  558.785522  175.703201  300.911896  45.703114   
3  144  1.277694  0.098911  536.960510  157.947479  246.560440  64.607643   
4  144  1.288991  0.147066  551.145813  174.888947  319.263397  51.905193   
5  144  1.364431  0.161957  541.638977  153.364273  260.940460  65.110550   
6  144  1.282912  0.123370  553.427124  173.801483  301.091675  54.246502   
7  144  1.323903  0.158135  543.402466  183.066711  310.318268  61.551853   
8  144  1.318927  0.147725  544.851257  172.988129  327.682922  54.185471   
9  144  1.289769  0.134671  543.180176  169.330093  311.361938  61.943439   

          사구  
0  13.747844  
1   4.188322  
2  13.153437  
3   6.894721  
4  12.905494  
5   3.143080  
6  13.077097  
7   8.934321  
8  13.575776  
9  15.627257

In [237]:
# 
df_raw_y = hitter[['희생플라이']]# 목표변수
df_raw_x = hitter[['경기수', '배럴지수_평균', '배럴비율', '타수', '안타', '루타', '볼넷','사구']] # 독립변수

# train, test set 나누기
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_x, df_raw_y, test_size = 0.3, random_state = 1234)

print('train data x size : {}'.format(df_train_x.shape))
print('train data y size : {}'.format(df_train_y.shape))
print('test data x size : {}'.format(df_test_x.shape))
print('test data y size : {}'.format(df_test_y.shape))

xgb_final = xgb.XGBRegressor(random_state = 1234)

xgb_final.fit(df_train_x, df_train_y)
print('----------------------------')
print('Score on training set: {:.3f}'.format(xgb_final.score(df_train_x, df_train_y)))
print('Score on test set: {:.3f}'.format(xgb_final.score(df_test_x, df_test_y)))

train data x size : (648, 8)
train data y size : (648, 1)
test data x size : (278, 8)
test data y size : (278, 1)
----------------------------
Score on training set: 1.000
Score on test set: 0.473


In [238]:
pred = xgb_final.predict(df_t)
pred

array([4.5001583, 7.808949 , 5.4922705, 5.559728 , 4.344136 , 6.5860815,
       4.6737313, 5.2969832, 5.2647743, 6.417488 ], dtype=float32)

In [239]:
df_t['희생플라이'] = pred
df_t

경기수   배럴지수_평균      배럴비율          타수          안타          루타         볼넷  \
0  144  1.305213  0.163905  536.263000  170.296707  314.071686  46.436382   
1  144  1.319997  0.138354  541.669373  164.822311  279.612488  62.531487   
2  144  1.276051  0.124472  558.785522  175.703201  300.911896  45.703114   
3  144  1.277694  0.098911  536.960510  157.947479  246.560440  64.607643   
4  144  1.288991  0.147066  551.145813  174.888947  319.263397  51.905193   
5  144  1.364431  0.161957  541.638977  153.364273  260.940460  65.110550   
6  144  1.282912  0.123370  553.427124  173.801483  301.091675  54.246502   
7  144  1.323903  0.158135  543.402466  183.066711  310.318268  61.551853   
8  144  1.318927  0.147725  544.851257  172.988129  327.682922  54.185471   
9  144  1.289769  0.134671  543.180176  169.330093  311.361938  61.943439   

          사구     희생플라이  
0  13.747844  4.500158  
1   4.188322  7.808949  
2  13.153437  5.492270  
3   6.894721  5.559728  
4  12.905494  4.344136  
5   3.143080  6.586082  
6  13.077097  4.673731  
7   8.934321  5.296983  
8  13.575776  5.264774  
9  15.627257  6.417488

In [240]:
df_t['출루율'] = (df_t['안타'] + df_t['볼넷'] + df_t['사구'])/(df_t['타수'] + df_t['볼넷'] + df_t['사구'] + df_t['희생플라이'])
df_t['장타율'] = df_t['루타'] / df_t['타수']
df_t['OPS'] = df_t['출루율'] + df_t['장타율']

In [241]:
df_t

경기수   배럴지수_평균      배럴비율          타수          안타          루타         볼넷  \
0  144  1.305213  0.163905  536.263000  170.296707  314.071686  46.436382   
1  144  1.319997  0.138354  541.669373  164.822311  279.612488  62.531487   
2  144  1.276051  0.124472  558.785522  175.703201  300.911896  45.703114   
3  144  1.277694  0.098911  536.960510  157.947479  246.560440  64.607643   
4  144  1.288991  0.147066  551.145813  174.888947  319.263397  51.905193   
5  144  1.364431  0.161957  541.638977  153.364273  260.940460  65.110550   
6  144  1.282912  0.123370  553.427124  173.801483  301.091675  54.246502   
7  144  1.323903  0.158135  543.402466  183.066711  310.318268  61.551853   
8  144  1.318927  0.147725  544.851257  172.988129  327.682922  54.185471   
9  144  1.289769  0.134671  543.180176  169.330093  311.361938  61.943439   

          사구     희생플라이       출루율       장타율       OPS  
0  13.747844  4.500158  0.383529  0.585667  0.969197  
1   4.188322  7.808949  0.375759  0.516205  0.891964  
2  13.153437  5.492270  0.376419  0.538511  0.914930  
3   6.894721  5.559728  0.373683  0.459178  0.832861  
4  12.905494  4.344136  0.386425  0.579272  0.965697  
5   3.143080  6.586082  0.359490  0.481761  0.841251  
6  13.077097  4.673731  0.385538  0.544049  0.929588  
7   8.934321  5.296983  0.409494  0.571065  0.980559  
8  13.575776  5.264774  0.389639  0.601417  0.991057  
9  15.627257  6.417488  0.393675  0.573220  0.966896

1. 양의지 : 76232
2. 강백호 : 68050
3. 최정 : 75847
4. 이정후 : 67341
5. 채은성 : 79192
6. 김재환 : 78224
7. 전준우 : 78513
8. 김현수 : 76290
9. 박건우 : 79215
10. 로맥 : 67872